'use client'

import { useEffect, useRef, useState } from 'react'

const TARGETS: Record<string, { label: string; code: string }> = {
  pyspark: {
    label: 'schema.py',
    code: `<span class="c"># generated by daco</span>
<span class="k">from</span> pyspark.sql.types <span class="k">import</span> *

daily_metrics_schema = <span class="a">StructType</span>([
  <span class="a">StructField</span>(<span class="s">"customer_id"</span>, <span class="hl">StringType</span>()),
  <span class="a">StructField</span>(<span class="s">"date"</span>, <span class="hl">DateType</span>()),
  <span class="a">StructField</span>(<span class="s">"total_orders"</span>, <span class="hl">IntegerType</span>()),
  <span class="a">StructField</span>(<span class="s">"revenue"</span>, <span class="hl">DoubleType</span>()),
])`,
  },
  dbt: {
    label: 'models/daily_metrics.yml',
    code: `<span class="c"># generated by daco</span>
<span class="k">version</span><span class="pun">:</span> <span class="n">2</span>

<span class="k">models</span><span class="pun">:</span>
  - <span class="k">name</span><span class="pun">:</span> <span class="a">daily_metrics</span>
    <span class="k">description</span><span class="pun">:</span> <span class="s">"Daily customer metrics"</span>
    <span class="k">columns</span><span class="pun">:</span>
      - <span class="k">name</span><span class="pun">:</span> <span class="hl">customer_id</span>
        <span class="k">tests</span><span class="pun">:</span> [not_null]
      - <span class="k">name</span><span class="pun">:</span> <span class="hl">date</span>
        <span class="k">tests</span><span class="pun">:</span> [not_null]
      - <span class="k">name</span><span class="pun">:</span> <span class="hl">total_orders</span>
      - <span class="k">name</span><span class="pun">:</span> <span class="hl">revenue</span>`,
  },
  pydantic: {
    label: 'models.py',
    code: `<span class="c"># generated by daco</span>
<span class="k">from</span> datetime <span class="k">import</span> date
<span class="k">from</span> pydantic <span class="k">import</span> <span class="a">BaseModel</span>

<span class="k">class</span> <span class="a">DailyMetrics</span>(<span class="n">BaseModel</span>):
    <span class="hl">customer_id</span>: <span class="n">str</span>
    <span class="hl">date</span>: <span class="n">date</span>
    <span class="hl">total_orders</span>: <span class="n">int</span>
    <span class="hl">revenue</span>: <span class="n">float</span>`,
  },
  go: {
    label: 'types.go',
    code: `<span class="c">// generated by daco</span>
<span class="k">package</span> analytics

<span class="k">import</span> <span class="s">"time"</span>

<span class="k">type</span> <span class="a">DailyMetrics</span> <span class="k">struct</span> {
    <span class="hl">CustomerID</span>   <span class="n">string</span>    \`json:"customer_id"\`
    <span class="hl">Date</span>         <span class="n">time.Time</span> \`json:"date"\`
    <span class="hl">TotalOrders</span>  <span class="n">int</span>       \`json:"total_orders"\`
    <span class="hl">Revenue</span>      <span class="n">float64</span>   \`json:"revenue"\`
}`,
  },
  typescript: {
    label: 'types.ts',
    code: `<span class="c">// generated by daco</span>
<span class="k">export interface</span> <span class="a">DailyMetrics</span> {
  <span class="hl">customer_id</span>: <span class="n">string</span>;
  <span class="hl">date</span>: <span class="n">string</span>;  <span class="c">// ISO 8601</span>
  <span class="hl">total_orders</span>: <span class="n">number</span>;
  <span class="hl">revenue</span>: <span class="n">number</span>;
}

<span class="k">export const</span> <span class="a">dailyMetricsSchema</span> = z.<span class="a">object</span>({
  customer_id: z.<span class="n">string</span>(),
  date: z.<span class="n">string</span>().date(),
  total_orders: z.<span class="n">number</span>().int(),
  revenue: z.<span class="n">number</span>(),
});`,
  },
}

const ORDER = ['pyspark', 'dbt', 'pydantic', 'go', 'typescript']

export default function Hero() {
  const [activeTab, setActiveTab] = useState('pyspark')
  const [outputLabel, setOutputLabel] = useState(TARGETS.pyspark.label)
  const [outputCode, setOutputCode] = useState(TARGETS.pyspark.code)
  const [codeVisible, setCodeVisible] = useState(true)
  const [copied, setCopied] = useState(false)
  const userInteracted = useRef(false)
  const idxRef = useRef(0)
  const timerRef = useRef<ReturnType<typeof setInterval> | null>(null)
  const morphRef = useRef<HTMLDivElement>(null)

  function switchTo(key: string) {
    setCodeVisible(false)
    setTimeout(() => {
      setActiveTab(key)
      setOutputLabel(TARGETS[key].label)
      setOutputCode(TARGETS[key].code)
      setCodeVisible(true)
    }, 180)
  }

  function startCycle() {
    if (timerRef.current) clearInterval(timerRef.current)
    timerRef.current = setInterval(() => {
      if (userInteracted.current) return
      idxRef.current = (idxRef.current + 1) % ORDER.length
      switchTo(ORDER[idxRef.current])
    }, 2800)
  }

  useEffect(() => {
    startCycle()
    const el = morphRef.current
    if (!el) return
    const io = new IntersectionObserver((entries) => {
      entries.forEach((e) => {
        if (e.isIntersecting && !userInteracted.current) startCycle()
        else if (timerRef.current) clearInterval(timerRef.current)
      })
    }, { threshold: 0.2 })
    io.observe(el)
    return () => {
      if (timerRef.current) clearInterval(timerRef.current)
      io.disconnect()
    }
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  function handleTabClick(key: string) {
    userInteracted.current = true
    idxRef.current = ORDER.indexOf(key)
    switchTo(key)
  }

  function handleCopy() {
    navigator.clipboard?.writeText('brew install dacolabs/tap/daco')
    setCopied(true)
    setTimeout(() => setCopied(false), 1400)
  }

  return (
    <header className="hero">
      <div className="container hero-inner">
        <div>
          <span className="hero-eyebrow">
            <span className="pill">NEW</span>
            OpenDPI 1.0 is now stable
            <span className="arrow">→</span>
          </span>
          <h1 className="hero-title">
            Build data pipelines <span className="accent">locally</span>.
          </h1>
          <p className="hero-sub">
            Daco gives data engineers the local development experience software engineers already have.
            Define your data products with OpenDPI, then build, test, and translate them without leaving your editor.
          </p>
          <div className="hero-cta-row">
            <a href="#demo" className="btn-primary">
              Book a demo
              <svg width="14" height="14" viewBox="0 0 14 14" fill="none">
                <path d="M2 7h10m0 0L7 2m5 5l-5 5" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"/>
              </svg>
            </a>
            <div className="hero-install">
              <span className="prompt">$</span>
              <span>brew install dacolabs/tap/daco</span>
              <button className="copy" onClick={handleCopy} title="Copy">
                {copied ? (
                  <span style={{ color: 'var(--yellow)', fontSize: '11px' }}>copied</span>
                ) : (
                  <svg width="12" height="12" viewBox="0 0 12 12" fill="none">
                    <rect x="3.5" y="3.5" width="6" height="6" rx="1" stroke="currentColor" strokeWidth="1.2"/>
                    <path d="M3 1.5h5.5A1.5 1.5 0 0 1 10 3v5.5" stroke="currentColor" strokeWidth="1.2" strokeLinecap="round"/>
                  </svg>
                )}
              </button>
            </div>
          </div>
        </div>

        <div className="morph-panel" ref={morphRef}>
          <div className="morph-header">
            <div className="morph-tabs">
              {ORDER.map((key) => (
                <button
                  key={key}
                  className={`morph-tab${activeTab === key ? ' is-active' : ''}`}
                  onClick={() => handleTabClick(key)}
                >
                  {key}
                </button>
              ))}
            </div>
          </div>
          <div className="morph-body">
            <div className="morph-col">
              <div className="morph-col-label">dataproduct.yaml</div>
              <pre className="code" dangerouslySetInnerHTML={{ __html: `<span class="k">opendpi</span><span class="pun">:</span> <span class="s">"1.0.0"</span>

<span class="k">info</span><span class="pun">:</span>
  <span class="k">title</span><span class="pun">:</span> <span class="s">"Customer Analytics"</span>
  <span class="k">version</span><span class="pun">:</span> <span class="s">"2.1.0"</span>

<span class="k">connections</span><span class="pun">:</span>
  <span class="k">analytics_db</span><span class="pun">:</span>
    <span class="k">type</span><span class="pun">:</span> postgresql
    <span class="k">host</span><span class="pun">:</span> analytics.db

<span class="k">ports</span><span class="pun">:</span>
  <span class="a">daily_metrics</span><span class="pun">:</span>
    <span class="k">schema</span><span class="pun">:</span>
      <span class="k">type</span><span class="pun">:</span> <span class="hl">object</span>
      <span class="k">properties</span><span class="pun">:</span>
        <span class="k">customer_id</span><span class="pun">:</span> <span class="hl">{ type: string }</span>
        <span class="k">date</span><span class="pun">:</span> <span class="hl">{ type: string, format: date }</span>
        <span class="k">revenue</span><span class="pun">:</span> <span class="hl">{ type: number }</span>` }} />
            </div>
            <div className="morph-arrow">
              <svg width="22" height="22" viewBox="0 0 22 22" fill="none">
                <path d="M3 11h16m0 0L13 5m6 6l-6 6" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"/>
              </svg>
            </div>
            <div className="morph-col">
              <div className="morph-col-label">{outputLabel}</div>
              <pre
                className="code"
                style={{ opacity: codeVisible ? 1 : 0, transform: codeVisible ? 'translateY(0)' : 'translateY(4px)' }}
                dangerouslySetInnerHTML={{ __html: outputCode }}
              />
            </div>
          </div>
        </div>
      </div>
    </header>
  )
}
